### ISSUE TITLE
Interpolation problems in `KumbhSans[YOPQ,wght].ttf`

### ISSUE THREAD

**Issue by behdad** [xconsau/KumbhSans#15]
Hello!

This is an automatically-generated report about possible interpolation problems in `KumbhSans[YOPQ,wght].ttf`, as found in the Google Fonts catalog.

The particular version of the font that was tested was [archive:](archive:).

To download a PDF version of this report with helpful visuals of the problems, click [here](https://github.com/behdad/google-fonts-ofl-interpolatable-results/raw/8ce3e0535f17cd069e91df45e252462bf74a2cc4/reports/KumbhSans%5BYOPQ%2Cwght%5D.ttf.pdf); Or to view it on the GitHub website, click [here](https://github.com/behdad/google-fonts-ofl-interpolatable-results/blob/8ce3e0535f17cd069e91df45e252462bf74a2cc4/reports/KumbhSans%5BYOPQ%2Cwght%5D.ttf.pdf).

The report follows:
```
Glyph arrowdown was not compatible:
  Masters: '', 'wght=100.0':
    Contour 0 start point differs: 0 in '', 3 in 'wght=100.0'; reversed: False
  Masters: '', 'wght=900.0':
    Contour 0 start point differs: 0 in '', 3 in 'wght=900.0'; reversed: False
  Masters: 'YOPQ=40.0', 'YOPQ=40.0 wght=100.0':
    Contour 0 start point differs: 0 in 'YOPQ=40.0', 3 in 'YOPQ=40.0 wght=100.0'; reversed: False
  Masters: 'YOPQ=40.0', 'YOPQ=40.0 wght=900.0':
    Contour 0 start point differs: 0 in 'YOPQ=40.0', 3 in 'YOPQ=40.0 wght=900.0'; reversed: False
Glyph arrowup was not compatible:
  Masters: '', 'wght=100.0':
    Contour 0 start point differs: 0 in '', 7 in 'wght=100.0'; reversed: False
  Masters: '', 'wght=900.0':
    Contour 0 start point differs: 0 in '', 7 in 'wght=900.0'; reversed: False
  Masters: '', 'YOPQ=40.0 wght=900.0':
    Contour 0 start point differs: 0 in '', 7 in 'YOPQ=40.0 wght=900.0'; reversed: False
Glyph guillemotleft was not compatible:
  Masters: '', 'YOPQ=40.0':
    Contour order differs: [0, 1] in '', [1, 0] in 'YOPQ=40.0'
  Masters: 'YOPQ=40.0', 'YOPQ=40.0 wght=100.0':
    Contour order differs: [0, 1] in 'YOPQ=40.0', [1, 0] in 'YOPQ=40.0 wght=100.0'
Glyph infinity was not compatible:
  Masters: '', 'wght=100.0':
    Contour order differs: [0, 1, 2] in '', [0, 2, 1] in 'wght=100.0'
  Masters: 'YOPQ=40.0', 'YOPQ=40.0 wght=100.0':
    Contour order differs: [0, 1, 2] in 'YOPQ=40.0', [0, 2, 1] in 'YOPQ=40.0 wght=100.0'
```

This report was generated using the `fonttools varLib.interpolatable` tool.  We understand that sometimes the tool generates false-positives.  Particularly for more complicated font designs.  If you did not find this report useful, please apologize and ignore & close it.

To give feedback about this report, please file an issue or open a discussion at [fonttools](https://github.com/fonttools/fonttools).

**Comment by xconsau** [comment]
Hello Behdad,

Thank you for testing and reporting the issue. I have compiled the new [var TTF](https://github.com/xconsau/KumbhSans/blob/master/fonts/variable/KumbhSans%5BYOPQ%2Cwght%5D.ttf) after necessary corrections. The source UFO files are also updated. Please let me know if this one has any errors.

**Comment by behdad** [comment]
New file looks good. Here's the new report.
[out.pdf](https://github.com/xconsau/KumbhSans/files/13461618/out.pdf)

**Comment by xconsau** [comment]
Great. Will it be required to create an issue on googlefonts repo for this update?

**Comment by behdad** [comment]
> Great. Will it be required to create an issue on googlefonts repo for this update?

Do you know who your Google Fonts contact is? Can you tag them here?

cc @davelab6

**Comment by xconsau** [comment]
> Do you know who your Google Fonts contact is? Can you tag them here?

Yes, @RosaWagner . Do we need to raise a ticket for this update?

**Comment by RosaWagner** [comment]
Hi @xconsau yes you can create an issue in the google/fonts repo, someone will onboard the update ;)

**Comment by xconsau** [comment]
Thank you, Rosalie.
