### ISSUE TITLE
I want to use KumbhSans in IVORY UI

### ISSUE THREAD

**Issue by kanthvallampati** [xconsau/KumbhSans#4]
Hi Saurabh,

I am the creator and maintainer of IVORY UI - http://ivoryui.com. Currently I am using Montserrat font in IVORY UI, and I would like to use KumbhSans instead of Montserrat. I know it is free use, but I would like to have your confirmation.

Let me know your thoughts on this.

**Comment by xconsau** [comment]
Hello Lakshmikanth,

Thank you for considering Kumbh Sans for your project. Yes, you can use it for free.
