### ISSUE TITLE
This is not an optical axis

### ISSUE THREAD

**Issue by RosaWagner** [xconsau/KumbhSans#9]
We may need to change it a "contrast axis" or something like that. I'll bring the matter to @davelab6 to advise better

**Comment by xconsau** [comment]
No problem, we can assign appropriate axis (whichever is applicable).

**Comment by davelab6** [comment]
I'd like to set up a public (recorded & posted to YouTube) video call with you and @dberlow so you can better understand the `YOPQ` and `opsz` axes; what you have now is already very close to his `YOPQ` axis, but not quote - there are some metrics/kerning changes, for example. 

The quick thing is to make the current axis a true `YOPQ`; the larger effort will be to make a full set of `opsz` adjustments.

**Comment by xconsau** [comment]
Great information. The current adjustment looks closest to [YOPQ](https://variationsguide.typenetwork.com/#yopq). We can discuss this in the call and get appropriate solution.

**Comment by RosaWagner** [comment]
Reporting solution discussed in this issue: https://github.com/google/fonts/issues/2759

```

label:             Contrast (Geometric)
code:              CTGO
default, min, max: 0,0..100

0 : Low
100 : High
```
